osx_image: xcode7.3
language: objective-c
xcode_project: ClosuresKit.xcodeproj
script: xcodebuild -project ClosuresKit.xcodeproj -scheme "ClosuresKit" 
        -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'